// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using csharp_groep31.Data;

#nullable disable

namespace csharp_groep31.Migrations
{
    [DbContext(typeof(ZooContext))]
    [Migration("20260108205840_Groep31")]
    partial class Groep31
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("csharp_groep31.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityPattern")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DietaryClass")
                        .HasColumnType("int");

                    b.Property<int?>("EnclosureId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecurityRequirement")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<double>("SpaceRequirement")
                        .HasColumnType("float");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EnclosureId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityPattern = 1,
                            CategoryId = 2,
                            DietaryClass = 0,
                            EnclosureId = 6,
                            Name = "Thijs",
                            SecurityRequirement = 0,
                            Size = 1,
                            SpaceRequirement = 0.80000000000000004,
                            Species = "Parrot"
                        },
                        new
                        {
                            Id = 2,
                            ActivityPattern = 2,
                            CategoryId = 1,
                            DietaryClass = 0,
                            EnclosureId = 3,
                            Name = "Jan",
                            SecurityRequirement = 2,
                            Size = 4,
                            SpaceRequirement = 12.0,
                            Species = "Polar Bear"
                        },
                        new
                        {
                            Id = 3,
                            ActivityPattern = 2,
                            CategoryId = 1,
                            DietaryClass = 3,
                            EnclosureId = 2,
                            Name = "Max",
                            SecurityRequirement = 1,
                            Size = 4,
                            SpaceRequirement = 12.0,
                            Species = "Giraffe"
                        },
                        new
                        {
                            Id = 4,
                            ActivityPattern = 0,
                            CategoryId = 1,
                            DietaryClass = 3,
                            EnclosureId = 2,
                            Name = "Eva",
                            SecurityRequirement = 0,
                            Size = 3,
                            SpaceRequirement = 6.0,
                            Species = "Zebra"
                        },
                        new
                        {
                            Id = 5,
                            ActivityPattern = 2,
                            CategoryId = 2,
                            DietaryClass = 0,
                            EnclosureId = 6,
                            Name = "Thomas",
                            SecurityRequirement = 0,
                            Size = 1,
                            SpaceRequirement = 0.80000000000000004,
                            Species = "Parrot"
                        },
                        new
                        {
                            Id = 6,
                            ActivityPattern = 1,
                            CategoryId = 1,
                            DietaryClass = 1,
                            EnclosureId = 2,
                            Name = "Daan",
                            SecurityRequirement = 1,
                            Size = 2,
                            SpaceRequirement = 3.0,
                            Species = "Bonobo"
                        },
                        new
                        {
                            Id = 7,
                            ActivityPattern = 2,
                            CategoryId = 2,
                            DietaryClass = 2,
                            EnclosureId = 6,
                            Name = "Sanne",
                            SecurityRequirement = 0,
                            Size = 1,
                            SpaceRequirement = 1.0,
                            Species = "Owl"
                        },
                        new
                        {
                            Id = 8,
                            ActivityPattern = 2,
                            CategoryId = 1,
                            DietaryClass = 0,
                            EnclosureId = 1,
                            Name = "Thijs",
                            SecurityRequirement = 2,
                            Size = 4,
                            SpaceRequirement = 8.0,
                            Species = "Lion"
                        },
                        new
                        {
                            Id = 9,
                            ActivityPattern = 1,
                            CategoryId = 3,
                            DietaryClass = 1,
                            EnclosureId = 2,
                            Name = "Anouk",
                            SecurityRequirement = 1,
                            Size = 1,
                            SpaceRequirement = 1.0,
                            Species = "Iguana"
                        },
                        new
                        {
                            Id = 10,
                            ActivityPattern = 2,
                            CategoryId = 3,
                            DietaryClass = 3,
                            EnclosureId = 3,
                            Name = "Jayden",
                            SecurityRequirement = 2,
                            Size = 4,
                            SpaceRequirement = 10.0,
                            Species = "Crocodile"
                        },
                        new
                        {
                            Id = 11,
                            ActivityPattern = 0,
                            CategoryId = 4,
                            DietaryClass = 1,
                            EnclosureId = 7,
                            Name = "Sem",
                            SecurityRequirement = 2,
                            Size = 5,
                            SpaceRequirement = 25.0,
                            Species = "Great White Shark"
                        },
                        new
                        {
                            Id = 12,
                            ActivityPattern = 0,
                            CategoryId = 1,
                            DietaryClass = 3,
                            EnclosureId = 3,
                            Name = "Daan",
                            SecurityRequirement = 2,
                            Size = 4,
                            SpaceRequirement = 12.0,
                            Species = "Polar Bear"
                        },
                        new
                        {
                            Id = 13,
                            ActivityPattern = 0,
                            CategoryId = 1,
                            DietaryClass = 4,
                            EnclosureId = 3,
                            Name = "Bas",
                            SecurityRequirement = 2,
                            Size = 4,
                            SpaceRequirement = 12.0,
                            Species = "Polar Bear"
                        },
                        new
                        {
                            Id = 14,
                            ActivityPattern = 1,
                            CategoryId = 3,
                            DietaryClass = 3,
                            EnclosureId = 2,
                            Name = "Rick",
                            SecurityRequirement = 1,
                            Size = 1,
                            SpaceRequirement = 1.0,
                            Species = "Iguana"
                        },
                        new
                        {
                            Id = 15,
                            ActivityPattern = 1,
                            CategoryId = 2,
                            DietaryClass = 1,
                            EnclosureId = 6,
                            Name = "Lucas",
                            SecurityRequirement = 0,
                            Size = 1,
                            SpaceRequirement = 0.80000000000000004,
                            Species = "Parrot"
                        },
                        new
                        {
                            Id = 16,
                            ActivityPattern = 2,
                            CategoryId = 3,
                            DietaryClass = 4,
                            EnclosureId = 3,
                            Name = "Bram",
                            SecurityRequirement = 2,
                            Size = 4,
                            SpaceRequirement = 10.0,
                            Species = "Crocodile"
                        },
                        new
                        {
                            Id = 17,
                            ActivityPattern = 0,
                            CategoryId = 2,
                            DietaryClass = 4,
                            EnclosureId = 4,
                            Name = "Lars",
                            SecurityRequirement = 0,
                            Size = 1,
                            SpaceRequirement = 1.2,
                            Species = "Penguin"
                        },
                        new
                        {
                            Id = 18,
                            ActivityPattern = 0,
                            CategoryId = 1,
                            DietaryClass = 2,
                            EnclosureId = 3,
                            Name = "Bram",
                            SecurityRequirement = 2,
                            Size = 4,
                            SpaceRequirement = 12.0,
                            Species = "Polar Bear"
                        },
                        new
                        {
                            Id = 19,
                            ActivityPattern = 0,
                            CategoryId = 1,
                            DietaryClass = 4,
                            EnclosureId = 5,
                            Name = "Anne",
                            SecurityRequirement = 0,
                            Size = 1,
                            SpaceRequirement = 0.80000000000000004,
                            Species = "Bat"
                        },
                        new
                        {
                            Id = 20,
                            ActivityPattern = 1,
                            CategoryId = 1,
                            DietaryClass = 2,
                            EnclosureId = 3,
                            Name = "Lucas",
                            SecurityRequirement = 2,
                            Size = 4,
                            SpaceRequirement = 12.0,
                            Species = "Polar Bear"
                        });
                });

            modelBuilder.Entity("csharp_groep31.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mammals"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Birds"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Reptiles"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fish"
                        });
                });

            modelBuilder.Entity("csharp_groep31.Models.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Climate")
                        .HasColumnType("int");

                    b.Property<int>("HabitatType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecurityLevel")
                        .HasColumnType("int");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Climate = 0,
                            HabitatType = 0,
                            Name = "Agressive land animal enclosure",
                            SecurityLevel = 2,
                            Size = 1502.0
                        },
                        new
                        {
                            Id = 2,
                            Climate = 0,
                            HabitatType = 0,
                            Name = "Non-agressive land animal enclosure",
                            SecurityLevel = 1,
                            Size = 711.0
                        },
                        new
                        {
                            Id = 3,
                            Climate = 0,
                            HabitatType = 0,
                            Name = "Agressive ambhibious animal enclosure",
                            SecurityLevel = 2,
                            Size = 688.0
                        },
                        new
                        {
                            Id = 4,
                            Climate = 0,
                            HabitatType = 0,
                            Name = "Non-agressive ambhibious animal enclosure",
                            SecurityLevel = 0,
                            Size = 1284.0
                        },
                        new
                        {
                            Id = 5,
                            Climate = 0,
                            HabitatType = 0,
                            Name = "Agressive flying animal enclosure",
                            SecurityLevel = 1,
                            Size = 752.0
                        },
                        new
                        {
                            Id = 6,
                            Climate = 0,
                            HabitatType = 0,
                            Name = "Non-agressive flying animal enclosure",
                            SecurityLevel = 1,
                            Size = 893.0
                        },
                        new
                        {
                            Id = 7,
                            Climate = 0,
                            HabitatType = 0,
                            Name = "Agressive sea animal enclosure",
                            SecurityLevel = 2,
                            Size = 1586.0
                        },
                        new
                        {
                            Id = 8,
                            Climate = 0,
                            HabitatType = 0,
                            Name = "Non-agressive sea animal enclosure",
                            SecurityLevel = 1,
                            Size = 1269.0
                        });
                });

            modelBuilder.Entity("csharp_groep31.Models.Animal", b =>
                {
                    b.HasOne("csharp_groep31.Models.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("csharp_groep31.Models.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Enclosure");
                });

            modelBuilder.Entity("csharp_groep31.Models.Category", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("csharp_groep31.Models.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
